### ISSUE TITLE
Differential privacy learning

### ISSUE THREAD

**Issue by wlnancy** [dhasuda/Differential-Privacy-Lab#1]
I am really interested in the project you write, and I think it is very good, I want to learn more about it. so could you please give me or tell me some more information about the methods implemented in the project? My e-mail address is 945389942@qq.com. Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by dhasuda** [comment]
Sure! Is there anything more specific you are interested in about this project?

The basic idea of the architecture you can find [here](https://github.com/dhasuda/Differential-Privacy-Lab/blob/master/code/README.md)

The privatizer itself ([laplace privatizer](https://github.com/dhasuda/Differential-Privacy-Lab/blob/master/code/privatizers/laplacePrivatizer.py)) simply gets a random number from a Laplace Probability distribution and add it to the value. You can find the start of the theory behind it [here](https://github.com/dhasuda/Differential-Privacy-Lab/blob/master/Getting%20Started/4.%20Laplace%20Mechanism.md)

**Comment by dhasuda** [comment]
Also if you give me some context about your background, I can be more objective explaining it

**Comment by dhasuda** [comment]
Closing this issue, since I've contacted you via e-mail and it seems all sorted out! 🙌🏻
